[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "mkdir -p server/public",
  "ls -la dist/public/ || echo 'dist/public not found'",
  "cp -r dist/public/* server/public/ || echo 'copy failed - continuing anyway'",
  "ls -la server/public/ || echo 'server/public verified'"
]

[phases.start]
cmd = "node dist/index.js"