[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  "mkdir -p server/public",
  "cp -r dist/public/* server/public/"
]

[phases.start]
