# Railway deployment: 2025-07-22 15:45 - Enhanced server startup
[phases.build]
cmds = ["npm install", "npm run build", "ls -la dist/", "ls -la dist/public/"]

[phases.start]
cmd = "NODE_ENV=production PORT=$PORT node dist/index.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
PORT = "3000"